<a href="https://colab.research.google.com/github/kyxmgn/Linear-Algebra_ChE_2nd-Sem_2021-2022/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the 

$$A = \begin{bmatrix} 3 & 1 & 7\\4 & -8 &0 \\ 1 & 0 & 8\end{bmatrix} $$


$$A^T = \begin{bmatrix} 3 & 4 & 1\\1 & -8 &0 \\ 7 & 0 & 8\end{bmatrix} $$

This can now be achieved

In [ ]:
A = np.array ([
    [2 , 4, 7],
    [0 , -2, 8],
    [9, 1, -2]
])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 2,  0,  9],
       [ 4, -2,  1],
       [ 7,  8, -2]])

In [ ]:
AT2 = A.T
AT2

array([[ 2,  0,  9],
       [ 4, -2,  1],
       [ 7,  8, -2]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [2, 9, 1, 0],
    [-1, 0, 2, 8],
    [3, 2, 6, -6]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape


(4, 3)

Try to create 

In [ ]:
K = np.array([
    [-1, 0, 2, 0],
    [2, 8, 6, 5],
    [0, 7, 1, 3]
])
M = np.array([
    [1, 2, 2],
    [9, 0, 1],
    [-1, 6, 0],
    [-7, 8, 9]
])

In [ ]:
np.array_equiv(K, M)

False

In [ ]:
np.dot(K, M)

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In [ ]:
X.dot(M)

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In [ ]:
K @ M

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In [ ]:
np.matmul(K,M)

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In matrix dot

In [ ]:
X = np.array([
    [2, -1, 0, 4],
    [1, 2, -7, 5],
    [0, 2, 2, 1]
])
Y = np.array([
    [-1, -2, -3, 4],
    [2, 4, 6, 5],
    [3, 5, 7, 6]
])
Z = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [2, 3, 7, 6],
    [1, 8, -2, 3]
])
print(X.shape)
print(Y.shape)
print(Z.shape)

(3, 4)
(3, 4)
(4, 4)


In [ ]:
X @ Z

array([[  7,  38,   1,  24],
       [-10,  17, -62, -31],
       [  3,  10,   6,   7]])

In [ ]:
X @ Y

ValueError: ignored

If you would

In [ ]:
X @ Y.T

array([[16, 20, 25],
       [36, -7, -6],
       [-6, 25, 30]])

Rule 2:

LinAlg

In [ ]:
A = np.array([
    [2, 1, 0],
    [-1, 6, 4],
    [2, 9, 6]
])
np.linalg.det(A)

13.999999999999996

In [ ]:
B = np.array([
    [2, 1],
    [-1, 2]
])
np.linalg.det(B)

5.000000000000001

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2,2,4,4],
    [0,1,2,3],
    [3,6,9,2],
    [4,2,6,8]
])
np.linalg.det(B)

15.999999999999998

Inverse

In [ ]:
L = np.array([
              [2, 5, 9, 0],
              [1, 9, 2, 9],
              [2, 4, 5, 9],
              [1, 1, 0, 0]
])
M = np.linalg.inv(L)
M

array([[-0.04761905, -0.14285714,  0.14285714,  0.95238095],
       [ 0.04761905,  0.14285714, -0.14285714,  0.04761905],
       [ 0.0952381 , -0.04761905,  0.04761905, -0.23809524],
       [-0.06349206, -0.00529101,  0.11640212, -0.1005291 ]])

In [ ]:
L @ M

array([[ 1.00000000e+00, -6.93889390e-17,  6.93889390e-17,
         0.00000000e+00],
       [ 1.24900090e-16,  1.00000000e+00,  1.38777878e-17,
         1.38777878e-16],
       [ 1.24900090e-16, -6.07153217e-17,  1.00000000e+00,
         1.38777878e-16],
       [-7.63278329e-17,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])