<a href="https://colab.research.google.com/github/kyxmgn/Linear-Algebra_ChE_2nd-Sem_2021-2022/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Assignment 3: Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.


## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the 

$$
A = \left\{
    \begin{array}\
        2x + y \\ 
        4x - 11y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y +z \\
        -2x + 4y +24z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      -w-x+8y+6z \\
      32w+2x-11y+9z \\
      w-2x+3y+2z
    \end{array}
\right. \\
$$

$$
A=\begin{bmatrix} 2 & 1 \\ 4 & {-11}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & 1 \\ -2 & 4 & 24\end{bmatrix}\\
C=\begin{bmatrix} -1 & -1 & 8 & 6 \\ 32 & 2 & -11 & 9 \\ 1 & -2 & 3 & 2\end{bmatrix}\\
$$


$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [5, 4],
    [7, 1]
])
describe_mat(A)

Matrix:
[[5 4]
 [7 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
G = np.array([
    [1,1],
    [2,2],
    [3, 1]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]
 [3 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([11,21,31,41])
describe_mat(H)


Matrix:
[11 21 31 41]

Shape:	(4,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values**. We'll try to go through them.

### According to shape

### Row and Column Matrices

Row and column matrices

In [ ]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
## Declaring a Column Matrix
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



### Square Matrices

Square matrices are

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [ ]:
square_mat = np.array([
    [11,4,8],
    [3,98,1],
    [0,11,6]
])

non_square_mat = np.array([
    [11,4,8],
    [3,98,1]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[11  4  8]
 [ 3 98  1]
 [ 0 11  6]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[11  4  8]
 [ 3 98  1]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

### Null Matrix

A Null Matrix is a matrix

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


### Zero Matrix

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,4))
zero_mat_rct = np.zeros((3,3))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Ones Matrix

A ones matrix is

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,4))
ones_mat_rct = np.ones((3,3))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Diagonal Matrix

A Diagonal Matrix is

In [ ]:
np.array([
    [11,0,0],
    [0,8,0],
    [0,0,5]
])

array([[11,  0,  0],
       [ 0,  8,  0],
       [ 0,  0,  5]])

In [ ]:
d = np.diag([10,20,30,40,50])
#d.shape[0] == d.shape[1]
d

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

### Identity Matrix

An identity matrix is...

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Upper Triangular Matrix

Upper Triangular Matrix is

In [ ]:
np.array([
    [1,2,3,4],
    [3,4,5,6],
    [0,4,5,6],
    [7,8,9,0]
])

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 4, 5, 6],
       [7, 8, 9, 0]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

### Lower Triangular Matrix

Lower Triangular Matrix is

In [ ]:
np.tril(F)

array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [ ]:
np.array([
    [1,0,0],
    [4,5,0],
    [3,6,9]
])

array([[1, 0, 0],
       [4, 5, 0],
       [3, 6, 9]])

### Practice

1.Given the linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$

$$
\theta=\begin{bmatrix} 5 & 3 & -1 \end{bmatrix}
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix}
$$

3.Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \left\{\begin{array}
5x_1 + 7x_2 +8x_3\\
2x_1 + 2x_2 + 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

4.Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
H = \left\{\begin{array}
1x_1 \\
2x_1 + 2x_2\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

## Matrix Algebra

### Addition

In [ ]:
A = np.array([
    [3,5],
    [3,6],
    [9,7]
])
B = np.array([
    [3,6],
    [2,1],
    [1,0]
])
A+B

array([[ 6, 11],
       [ 5,  7],
       [10,  7]])

In [ ]:
2+A ##Broadcating
# 2*np.ones(A.shape)+A

array([[ 5,  7],
       [ 5,  8],
       [11,  9]])

### Subtraction

In [ ]:
A-B

array([[ 0, -1],
       [ 1,  5],
       [ 8,  7]])

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [ ]:
A*B

array([[ 9, 30],
       [ 6,  6],
       [ 9,  0]])

In [ ]:
2*A

array([[ 6, 10],
       [ 6, 12],
       [18, 14]])

In [ ]:
A@B

ValueError: ignored

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[1.00000000e+00, 8.33333333e-01],
       [1.50000000e+00, 6.00000000e+00],
       [9.00000000e+00, 7.00000000e+10]])

In [ ]:
np.add(A,B)

array([[ 6, 11],
       [ 5,  7],
       [10,  7]])

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
## Function Area
def mat_desc(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs it Square: {is_square}\n')
  else:
    print('\nMatrix is null\n\n')

In [ ]:
## Matrix Declarations
O = np.array([
    [8, 65, 7, 9],
    [2, 0, 21, 9],
    [3, 101, 6, 8]
])

P = np.array([
    [3, 89, 6],
    [9, 27, 68],
    [90, 8, 11],
    [2, 7, 88]
])

null_mat = np.array([])

R = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])

S = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])

In [ ]:
## Test Areas
mat_desc(O)

mat_desc(P)

mat_desc(null_mat)

mat_desc(R)

mat_desc(S)

Matrix:
[[  8  65   7   9]
 [  2   0  21   9]
 [  3 101   6   8]]

Shape:	(3, 4)
Rank:	2
Is it Square: False

Matrix:
[[ 3 89  6]
 [ 9 27 68]
 [90  8 11]
 [ 2  7 88]]

Shape:	(4, 3)
Rank:	2
Is it Square: False


Matrix is null


Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(3, 3)
Rank:	2
Is it Square: True

Matrix:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Shape:	(4, 4)
Rank:	2
Is it Square: True



### Task 2

Create a function named `mat_operations()` that takes in two matrices an input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the difference of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
print("Enter Row and Column Size of 1st Matrix: ", end="")
rowOne = int(input())
colOne = int(input())
print("Enter Row and Column Size of 2nd Matrix: ", end="")
rowTwo = int(input())
colTwo = int(input())

if rowOne==rowTwo and colOne==colTwo:
    mat_addOne = []
    print("\nEnter " +str(rowOne*colOne)+ " Elements for 1st Matrix: ")
    for i in range(rowOne):
        mat_addOne.append([])
        for j in range(colOne):
            num = int(input())
            mat_addOne[i].append(num)

    mat_addTwo = []
    print("\nEnter " +str(rowTwo*colTwo)+ " Elements for 2nd Matrix: ")
    for i in range(rowTwo):
        mat_addTwo.append([])
        for j in range(colTwo):
            num = int(input())
            mat_addTwo[i].append(num)

    mat_addThree = []
    for i in range(rowOne):
        mat_addThree.append([])
        for j in range(colTwo):
            mat_addThree[i].append(mat_addOne[i][j]+mat_addTwo[i][j])

    print("\nAddition Result:")
    for i in range(rowOne):
        for j in range(colOne):
            print(mat_addThree[i][j], end=" ")
        print()
else:
    print("\nDimension Error!")

Enter Row and Column Size of 1st Matrix: 3
3
Enter Row and Column Size of 2nd Matrix: 3
3

Enter 9 Elements for 1st Matrix: 
1
2
3
4
5
6
7
8
9

Enter 9 Elements for 2nd Matrix: 
0
0
0
0
0
0
0
0
0

Addition Result:
1 2 3 
4 5 6 
7 8 9 


In [ ]:
print("Enter Row and Column Size of 1st Matrix: ", end="")
rowOne = int(input())
colOne = int(input())
print("Enter Row and Column Size of 2nd Matrix: ", end="")
rowTwo = int(input())
colTwo = int(input())

if rowOne==rowTwo and colOne==colTwo:
    mat_subOne = []
    print("\nEnter " +str(rowOne*colOne)+ " Elements for 1st Matrix: ")
    for i in range(rowOne):
        mat_subOne.append([])
        for j in range(colOne):
            num = int(input())
            mat_subOne[i].append(num)

    mat_subTwo = []
    print("\nEnter " +str(rowTwo*colTwo)+ " Elements for 2nd Matrix: ")
    for i in range(rowTwo):
        mat_subTwo.append([])
        for j in range(colTwo):
            num = int(input())
            mat_subTwo[i].append(num)

    mat_subThree = []
    for i in range(rowOne):
        mat_subThree.append([])
        for j in range(colTwo):
            mat_subThree[i].append(mat_subOne[i][j]-mat_subTwo[i][j])

    print("\nSubtraction Result:")
    for i in range(rowOne):
        for j in range(colOne):
            print(mat_subThree[i][j], end=" ")
        print()
else:
    print("\nDimension Error!")

Enter Row and Column Size of 1st Matrix: 3
3
Enter Row and Column Size of 2nd Matrix: 3
3

Enter 9 Elements for 1st Matrix: 
1
2
3
4
5
6
7
8
9

Enter 9 Elements for 2nd Matrix: 
2
3
8
9
4
3
1
5
7

Subtraction Result:
-1 -1 -5 
-5 1 3 
6 3 2 


In [ ]:
print("Enter the Row Size of 1st Matrix: ", end="")
try:
    rOne = int(input())
    print("Enter the Column Size of 1st Matrix: ", end="")
    try:
        cOne = int(input())
        print("Enter " +str(rOne * cOne)+ " Elements: ", end="")
        mat_multOne = []
        for i in range(rOne):
            mat_multOne.append([])
            for j in range(cOne):
                try:
                    num = int(input())
                    mat_multOne[i].append(num)
                except ValueError:
                    print("\nInvalid Input!")
                    exit()
        print("\nEnter Row Size of 2nd Matrix: ", end="")
        try:
            rTwo = int(input())
            if cOne == rTwo:
                print("Enter Column Size of Second Matrix: ", end="")
                try:
                    cTwo = int(input())
                    print("Enter " +str(rTwo * cTwo)+ " Elements: ", end="")
                    mat_multTwo = []
                    for i in range(rTwo):
                        mat_multTwo.append([])
                        for j in range(cTwo):
                            try:
                                num = int(input())
                                mat_multTwo[i].append(num)
                            except ValueError:
                                print("\nInvalid Input!")
                                exit()

                    mat_multThree = []
                    for i in range(rOne):
                        mat_multThree.append([])
                        for j in range(cTwo):
                            sum = 0
                            for k in range(cOne):
                                sum = sum + (mat_multOne[i][k] * mat_multTwo[k][j])
                            mat_multThree[i].append(sum)

                    print("\nMultiplication Result of Two Given Matrix is:")
                    for i in range(rOne):
                        for j in range(cTwo):
                            print(mat_multThree[i][j], end=" ")
                        print()
                except ValueError:
                    print("\nInvalid Column Size!")
            else:
                print("\nMultiplication not possible!")
        except ValueError:
            print("\nInvalid Row Size!")
    except ValueError:
        print("\nInvalid Column Size!")
except ValueError:
    print("\nInvalid Row Size!")

Enter the Row Size of 1st Matrix: 3
Enter the Column Size of 1st Matrix: 4
Enter 12 Elements: 3
5
6
8
9
2
3
1
0
2
1
5

Enter Row Size of 2nd Matrix: 2

Multiplication not possible!


In [ ]:
print("Enter Row and Column Size of 1st Matrix: ", end="")
rowOne = int(input())
colOne = int(input())
print("Enter Row and Column Size of 2nd Matrix: ", end="")
rowTwo = int(input())
colTwo = int(input())

if rowOne==rowTwo and colOne==colTwo:
    mat_addOne = []
    print("\nEnter " +str(rowOne*colOne)+ " Elements for 1st Matrix: ")
    for i in range(rowOne):
        mat_addOne.append([])
        for j in range(colOne):
            num = int(input())
            mat_addOne[i].append(num)

    mat_addTwo = []
    print("\nEnter " +str(rowTwo*colTwo)+ " Elements for 2nd Matrix: ")
    for i in range(rowTwo):
        mat_addTwo.append([])
        for j in range(colTwo):
            num = int(input())
            mat_addTwo[i].append(num)

    mat_addThree = []
    for i in range(rowOne):
        mat_addThree.append([])
        for j in range(colTwo):
            mat_addThree[i].append(mat_addOne[i][j]+mat_addTwo[i][j])

    print("\nAddition Result:")
    for i in range(rowOne):
        for j in range(colOne):
            print(mat_addThree[i][j], end=" ")
        print()
else:
    print("\nDimension Error!")

Enter Row and Column Size of 1st Matrix: 3
4
Enter Row and Column Size of 2nd Matrix: 4
5

Dimension Error!


In [ ]:
print("Enter the Row Size of 1st Matrix: ", end="")
try:
    rOne = int(input())
    print("Enter the Column Size of 1st Matrix: ", end="")
    try:
        cOne = int(input())
        print("Enter " +str(rOne * cOne)+ " Elements: ", end="")
        mat_multOne = []
        for i in range(rOne):
            mat_multOne.append([])
            for j in range(cOne):
                try:
                    num = int(input())
                    mat_multOne[i].append(num)
                except ValueError:
                    print("\nInvalid Input!")
                    exit()
        print("\nEnter Row Size of 2nd Matrix: ", end="")
        try:
            rTwo = int(input())
            if cOne == rTwo:
                print("Enter Column Size of Second Matrix: ", end="")
                try:
                    cTwo = int(input())
                    print("Enter " +str(rTwo * cTwo)+ " Elements: ", end="")
                    mat_multTwo = []
                    for i in range(rTwo):
                        mat_multTwo.append([])
                        for j in range(cTwo):
                            try:
                                num = int(input())
                                mat_multTwo[i].append(num)
                            except ValueError:
                                print("\nInvalid Input!")
                                exit()

                    mat_multThree = []
                    for i in range(rOne):
                        mat_multThree.append([])
                        for j in range(cTwo):
                            sum = 0
                            for k in range(cOne):
                                sum = sum + (mat_multOne[i][k] * mat_multTwo[k][j])
                            mat_multThree[i].append(sum)

                    print("\nMultiplication Result of Two Given Matrix is:")
                    for i in range(rOne):
                        for j in range(cTwo):
                            print(mat_multThree[i][j], end=" ")
                        print()
                except ValueError:
                    print("\nInvalid Column Size!")
            else:
                print("\nMultiplication not possible!")
        except ValueError:
            print("\nInvalid Row Size!")
    except ValueError:
        print("\nInvalid Column Size!")
except ValueError:
    print("\nInvalid Row Size!")

Enter the Row Size of 1st Matrix: 4
Enter the Column Size of 1st Matrix: 3
Enter 12 Elements: 2
7
3
5
2
7
2
5
3
8
2
5

Enter Row Size of 2nd Matrix: 3
Enter Column Size of Second Matrix: 3
Enter 9 Elements: 9
0
1
2
3
6
3
6
1

Multiplication Result of Two Given Matrix is:
41 39 47 
70 48 24 
37 33 35 
91 36 25 
