<a href="https://colab.research.google.com/github/kyxmgn/Linear-Algebra_ChE_2nd-Sem_2021-2022/blob/main/Assignment_5_Magno%2C_Kassandra_Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Laboratory 6: Matrix Operation

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

The horizontal line of elements is called the row of the matrix that is denoted as m meanwhile, the vertical is the column of the matrix that is denoted as n. Jointly, the order of the matrix is represented as m x n. The transpose of a matrix is an operator which inverts the existing matrix by changing its row into column or column into row. For the matrix A, its transpose would be AT. Here, the transpose’s order will be written as n x m. 

$$A = \begin{bmatrix} 3 & 1 & 7\\4 & -8 &0 \\ 1 & 0 & 8\end{bmatrix} $$


$$A^T = \begin{bmatrix} 3 & 4 & 1\\1 & -8 &0 \\ 7 & 0 & 8\end{bmatrix} $$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array ([
    [2 , 4, 7],
    [0 , -2, 8],
    [9, 1, -2]
])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 2,  0,  9],
       [ 4, -2,  1],
       [ 7,  8, -2]])

In [ ]:
AT2 = A.T
AT2

array([[ 2,  0,  9],
       [ 4, -2,  1],
       [ 7,  8, -2]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
    [2, 9, 1, 0],
    [-1, 0, 2, 8],
    [3, 2, 6, -6]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape


(4, 3)

### Practice

In [ ]:
K = np.array([
    [-1, 0, 2, 0],
    [2, 8, 6, 5],
    [0, 7, 1, 3]
])
M = np.array([
    [1, 2, 2],
    [9, 0, 1],
    [-1, 6, 0],
    [-7, 8, 9]
])

In [ ]:
np.array_equiv(K, M)

False

In [ ]:
np.dot(K, M)

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In [ ]:
X.dot(M)

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In [ ]:
K @ M

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

In [ ]:
np.matmul(K,M)

array([[-3, 10, -2],
       [33, 80, 57],
       [41, 30, 34]])

## Dot Product / Inner Product

The Dot Product is also known as Vector Multiplication which is a method to compute a product of two matrices. It is done by getting the sum of the products of elements in regards with their position which is between the rows of the first matrix and columns of the second matrix.	Using the operator @, and the functions np.dot( ) and np.matmul( ), this can be executed in Python.

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$

In [ ]:
G = np.array([
    [3, 7],
    [0, 1]
])
H = np.array([
    [-2, 1],
    [0, 1]
])

In [ ]:
np.array_equiv(G,H)

False

In [ ]:
np.dot(G,H)

array([[-6, 10],
       [ 0,  1]])

In [ ]:
G.dot(H)

array([[-6, 10],
       [ 0,  1]])

In [ ]:
G @ H

array([[-6, 10],
       [ 0,  1]])

In [ ]:
np.matmul(G,H)

array([[-6, 10],
       [ 0,  1]])

In [ ]:
S = np.array([
    [4, 1, 0],
    [3, 7, -2],
    [1, 2, 3]
])
T = np.array([
    [9, 1, 3],
    [4, 2, 6],
    [0, -2, 6]
])

In [ ]:
S @ T

array([[40,  6, 18],
       [55, 21, 39],
       [17, -1, 33]])

In [ ]:
S.dot(T)

array([[40,  6, 18],
       [55, 21, 39],
       [17, -1, 33]])

In [ ]:
np.matmul(S,T)

array([[40,  6, 18],
       [55, 21, 39],
       [17, -1, 33]])

In [ ]:
np.dot(S,T)

array([[40,  6, 18],
       [55, 21, 39],
       [17, -1, 33]])

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

The two matrices in question must have the same inner dimensions. For instance, a matrix A which has dimension of  a x b where a and b are any integers. Then if we are executing a dot product, the matrix B should have a dimension of b x c where b and c are any integers as well. When the inner dimension of the two matrices is mismatched, the output on the Python would become “value error”. 
 


In [ ]:
X = np.array([
    [2, -1, 0, 4],
    [1, 2, -7, 5],
    [0, 2, 2, 1]
])
Y = np.array([
    [-1, -2, -3, 4],
    [2, 4, 6, 5],
    [3, 5, 7, 6]
])
Z = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [2, 3, 7, 6],
    [1, 8, -2, 3]
])
print(X.shape)
print(Y.shape)
print(Z.shape)

(3, 4)
(3, 4)
(4, 4)


In [ ]:
X @ Z

array([[  7,  38,   1,  24],
       [-10,  17, -62, -31],
       [  3,  10,   6,   7]])

In [ ]:
X @ Y

ValueError: ignored

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
X @ Y.T

array([[16, 20, 25],
       [36, -7, -6],
       [-6, 25, 30]])

In [ ]:
L = np.array([
    [2, 4, 6, 8]
])
M = np.array([
    [1, 3, 5, 7]
])
print(L.shape)
print(M.shape)

(1, 4)
(1, 4)


In [ ]:
M.T @ L

array([[ 2,  4,  6,  8],
       [ 6, 12, 18, 24],
       [10, 20, 30, 40],
       [14, 28, 42, 56]])

In [ ]:
L @ M.T

array([[100]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
F = np.array([
    [5, 9, 1],
    [2, 0, 5],
    [1, 4, 6]
])
G = np.array([
    [0, 1, 4],
    [7, 9, -4],
    [-3, 5, 2]
])
H = np.array([
    [2, 0, 1],
    [7, 1, 4],
    [4, 1, 0]
])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
F.dot(np.eye(3))

array([[5., 9., 1.],
       [2., 0., 5.],
       [1., 4., 6.]])

In [ ]:
np.array_equal(F@G, G@F)

False

In [ ]:
R = F @ (G @ H)
R

array([[701,  77, 424],
       [231,  45,  93],
       [489,  67, 278]])

In [ ]:
S = (F @ G) @ H
S

array([[701,  77, 424],
       [231,  45,  93],
       [489,  67, 278]])

In [ ]:
np.array_equal(R, L)

False

In [ ]:
np.array_equiv(R,S)

True

In [ ]:
np.eye(F)

TypeError: ignored

In [ ]:
F @ R

array([[6073,  857, 3235],
       [3847,  489, 2238],
       [4559,  659, 2464]])

In [ ]:
z_mat = np.zeros(F.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = F.dot(np.zeros(F.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z, z_mat)

True

In [ ]:
null_mat = np.empty(F.shape, dtype=float)
null = np.array(null_mat, dtype=float)
print(null)
np.allclose(a_dot_z, null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

Determinant is a unique integer that can be computed using a matrix that should be a square or in definition, the rows and columns of the matrix should be equal. It is useful in solving systems of linear equations [4]. Through using the function np.linalg.det( ), the determinant of the matrix would be solved. For instance, the given matrix here is a 2x2 matrix. To explain how it is solved, the method would be cross multiply then subtract to each other. 

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. 

In [ ]:
A = np.array([
    [2, 1, 0],
    [-1, 6, 4],
    [2, 9, 6]
])
np.linalg.det(A)

13.999999999999996

In [ ]:
B = np.array([
    [2, 1],
    [-1, 2]
])
np.linalg.det(B)

5.000000000000001

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2,2,4,4],
    [0,1,2,3],
    [3,6,9,2],
    [4,2,6,8]
])
np.linalg.det(B)

15.999999999999998

##Inverse

In order to obtain the solution to linear equations, the inverse of the matrix is used. Through this, we can determine a matrix's solvability and characteristic as a system of linear equations. For example, we have matrix A, its inverse is denoted by $A^{-1}$. When the determinant of a matrix is non-zero and it is a square matrix, it could be solved by the method called invertible matrix. To compute the inverse of the matrix in Python, the function np.linalg.inv() is used.

In [ ]:
K = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [2, 0, 2]
])

np.array(K @np.linalg.inv(K), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
L = np.array([
              [2, 5, 9, 0],
              [1, 9, 2, 9],
              [2, 4, 5, 9],
              [1, 1, 0, 0]
])
M = np.linalg.inv(L)
M

array([[-0.04761905, -0.14285714,  0.14285714,  0.95238095],
       [ 0.04761905,  0.14285714, -0.14285714,  0.04761905],
       [ 0.0952381 , -0.04761905,  0.04761905, -0.23809524],
       [-0.06349206, -0.00529101,  0.11640212, -0.1005291 ]])

In [ ]:
L @ M

array([[ 1.00000000e+00, -6.93889390e-17,  6.93889390e-17,
         0.00000000e+00],
       [ 1.24900090e-16,  1.00000000e+00,  1.38777878e-17,
         1.38777878e-16],
       [ 1.24900090e-16, -6.07153217e-17,  1.00000000e+00,
         1.38777878e-16],
       [-7.63278329e-17,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
J = np.array([
    [12,3,8,-2,0,9],
    [9,4,1,63,1,4],
    [4,14,94,-2,20,12],
    [75,42,98,2,78,4],
    [5,32,14,90,15,4],
    [23,18,-5,0,11,6]
])
J_inv = np.linalg.inv(J)
np.array(J @ J_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [2.5, 1.75],
    [1.0, 3.0]
])
weights = np.array([
    [0.3, 0.7]
])
k_grade = squad @ weights.T
k_grade


array([[1.975],
       [2.4  ]])

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
E = np.array([
    [1, 0, -1, 3],
    [2, 0, -5, 5],
    [9, 8, 3, 5],
    [-6, -1, 0, 4]
])
F = np.array([
    [2, 0, 4, 1],
    [8, 3, -1, -7],
    [8, 5, -3, 4],
    [6, -1, 6, 3]
])

print('Matrix E:')
print(E)
print('Matrix F:')
print(F)

Matrix E:
[[ 1  0 -1  3]
 [ 2  0 -5  5]
 [ 9  8  3  5]
 [-6 -1  0  4]]
Matrix F:
[[ 2  0  4  1]
 [ 8  3 -1 -7]
 [ 8  5 -3  4]
 [ 6 -1  6  3]]


 $A \cdot B \neq B \cdot A$

In [7]:
print('Matrix product EF:')
EF = np.matmul(E,F)
EF

Matrix product EF:


array([[ 12,  -8,  25,   6],
       [ -6, -30,  53,  -3],
       [136,  34,  49, -20],
       [  4,  -7,   1,  13]])

In [8]:
print('Matrix product FE:')
FE = np.matmul(F,E)
FE

Matrix product FE:


array([[ 32,  31,  10,  30],
       [ 47,  -1, -26,   6],
       [-33, -28, -42,  50],
       [ 40,  45,  17,  55]])

In [9]:
np.array_equal(EF, FE)

False

In [11]:
G = np.array([
    [2, 3, -4, 9],
    [2, 2, -2, -2],
    [0, 1, 6, 3],
    [-2, -9, 1, 8]
])
H = np.array([
    [1, 9, 3],
    [2, 3, 2],
    [3, 9, 4],
    [1, 6, 2]
])
I = np.array([
    [2, 4, 6],
    [9, 0, 1],
    [2, 6, 9]
])
GH = np.matmul(G,H)
HI = np.matmul(H,I)

print('Matrix G:')
print(G)
print('Matrix H:')
print(H)
print('Matrix I:')
print(I)

Matrix G:
[[ 2  3 -4  9]
 [ 2  2 -2 -2]
 [ 0  1  6  3]
 [-2 -9  1  8]]
Matrix H:
[[1 9 3]
 [2 3 2]
 [3 9 4]
 [1 6 2]]
Matrix I:
[[2 4 6]
 [9 0 1]
 [2 6 9]]


$A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [12]:
print('Matrix Product (GH)I:')
L = np.matmul(GH,I)
L

Matrix Product (GH)I:


array([[443, 104, 201],
       [-62, -20, -36],
       [785, 284, 501],
       [ 82, -60, -78]])

In [13]:
print('Matrix Product G(HI)')
R = np.matmul(G,HI)
R

Matrix Product G(HI)


array([[443, 104, 201],
       [-62, -20, -36],
       [785, 284, 501],
       [ 82, -60, -78]])

In [14]:
np.array_equal(L, R)

True

In [28]:
J = np.array([-1,3,2])
K = np.array([
    [0, 2, 3],
    [5, 6, 8],
    [2, 3, 1]
    ])
L = np.array([
    [1, 4, 9],
    [8, -1, 0],
    [5, 2, 1]
    ])
JK = np.matmul(J,K)
KL = np.matmul(K,L)
JL = np.matmul(J,L)

print('Matrix J')
print(J)
print('Matrix K:')
print(K)
print('Matrix L:')
print(L) 

Matrix J
[-1  3  2]
Matrix K:
[[0 2 3]
 [5 6 8]
 [2 3 1]]
Matrix L:
[[ 1  4  9]
 [ 8 -1  0]
 [ 5  2  1]]


$A\cdot(B+C) = A\cdot B + A\cdot C$

In [19]:
print('\n')
print('Distributing left multiplication')
print('Matrix Product J*(K + L):')
print(np.matmul(J,K+L))
print('Matrix Product (JK + JL):')
DL = JK+JL
DL




Distributing left multiplication
Matrix Product J*(K + L):
[52 19 16]
Matrix Product (JK + JL):


array([52, 19, 16])

In [20]:
D = J @ (K+L)
D

array([52, 19, 16])

In [21]:
np.array_equal(DL, D)

True

$(A+B)\cdot C = A\cdot C + B\cdot C$

In [31]:
print('Distributing right multiplication')
print('Matrix Product (J + K)*L:')
print(np.matmul(J+K,L))
print('Matrix Product (JL + KL):')
DR = JL + KL
DR

Distributing right multiplication
Matrix Product (J + K)*L:
[[ 64   1  -4]
 [126  27  46]
 [ 64   4  12]]
Matrix Product (JL + KL):


array([[ 64,   1,  -4],
       [126,  27,  46],
       [ 64,   4,  12]])

In [30]:
E = (J+K) @L
E

array([[ 64,   1,  -4],
       [126,  27,  46],
       [ 64,   4,  12]])

In [32]:
np.array_equal(DR, E)

True

In [40]:
N = np.array([
      [-1,-2,-3],
      [1, 2, -2],
      [0, 1, 2]
      ])
N

array([[-1, -2, -3],
       [ 1,  2, -2],
       [ 0,  1,  2]])

$A\cdot I = A$

In [41]:
NI = np.identity(3)
NI
O =N@NI
O

array([[-1., -2., -3.],
       [ 1.,  2., -2.],
       [ 0.,  1.,  2.]])

 $A\cdot \emptyset = \emptyset$ 

In [42]:
NZ = N.dot(np.zeros(N.shape))
NZ


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
P = N@NZ
P

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.array_equal(NZ,P)

True

## Conclusion

Through this laboratory activity, it proved that it is easier to solve multiplication of matrices through Google Collab than manually solving it. With inputting codes to our matrices, the program itself will automatically solve it  by clicking “Run”. Nonetheless, codes are a bit sensitive when inputted – not to mention some might be the same but will have a different outcome – one will find it convenient to learn and apply the codes every time they encounter matrix problems. Also, the rules and properties for matrix multiplication were guides for encoding as well so that one will not be confused on what codes are appropriate to apply. Learning through Google Colab requires patience yet it is interacting and interesting in some ways – like if one was to apply future calculations related to matrix multiplications such as inverse, determinants, dot product, and many more. 