<a href="https://colab.research.google.com/github/kyxmgn/Linear-Algebra_ChE_2nd-Sem_2021-2022/blob/main/Prelims.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


$$

B = \left\{

    \begin{array}\

        x+y+z \\ 

        3x -2y -z \\

        -x + 4y +2z

    \end{array}

\right. 
$$


$$

B = \left\{

    \begin{matrix}\

        x+y+z \\ 

        3x -2y -z \\

        -x + 4y +2z

    \end{matrix}

\right.
$$

In [1]:
import numpy as np
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c

array([1, 5, 7, 7, 9])

In [3]:
d = {0,1,2}
for x in d:
    print(x)

0
1
2


In [4]:
x = 1
while True:
    if x % 5 == 0:
        break
    print(x)
    x + = 1

SyntaxError: ignored

In [5]:
import numpy as np
X = np.array([
    [5,0,4],
    [4,-1,5],
    [3,-1,-6]
])
Y = np.triu(X)
Y

array([[ 5,  0,  4],
       [ 0, -1,  5],
       [ 0,  0, -6]])

In [7]:
def create_user (userid):
    print ("Successfully created user: {}" .format(userid))

userid = 2021_100001
create_user(2021-100100)

Successfully created user: -98079


In [8]:
import numpy as np
a = np.array([[1,2,3],[0,1,4]])
print (a.shape)

(2, 3)


In [9]:
x, y, z = 2, 4.0 , '3'
type (z)

str

In [10]:
i = 0
while i < 5:
    print(i)
    i +=1
    if i==3:
        break
else:
    print(0)

0
1
2


In [11]:
int1 = 10
int2 = 6
if int1 != int2:
    int2 = ++ int2
    print(int1 - int2)

4


In [13]:
P = np.array([
    [5,7,2],
    [2,3,3],
    [4,1,0]
])
Q = np.array([
    [2,2,-3],
    [0,0,1],
    [1,1,-3]
])
P + 2*Q

array([[ 9, 11, -4],
       [ 2,  3,  5],
       [ 6,  3, -6]])